SocketDev/socket-cli

- README.md
Signed-off-by: Jake Verbaten <raynos2@gmail.com>
> Add Socket badge to README

- README.md
Signed-off-by: Jake Verbaten <raynos2@gmail.com>
> Fix image URL for badge.

- LICENSE
I think changing the MIT license text works around the license
detection issues.
As for the other issues with dependencies, there's not much to do
other then to remove all the dependencies and write more code ourselves.
> Attempt to update the score.

- lib/commands/info/index.js
- lib/commands/report/create.js
- lib/commands/report/view.js
- lib/utils/api-helpers.js
Avoids Cloudflare timeout - should be removed once `report/view` is faster
> Auto-retry on 524 error

- lib/commands/login/index.js
- lib/commands/logout/index.js
- lib/commands/report/create.js
- lib/shadow/npm-injection.cjs
- lib/shadow/tty-server.cjs
- lib/utils/sdk.js
- lib/utils/settings.js
- test/socket-npm-fixtures/lacking-typosquat/package.json
- test/socket-npm.test.js
- tsconfig.json
- fixes a bug in tty sharing
- makes env variables more robust and override login file
- makes npm not complain when offline w/ wrapper by treating eager settings fetch as handled until used
> Fixes for offline / npm

- lib/utils/path-resolve.js
- package-lock.json
- package.json
- test/path-resolve.test.js
this restores recursive globbing and more closely aligns with the GitHub behaviors of analysis by default
> make argv parsing more tolerant and align with GH

- lib/commands/info/index.js
- package-lock.json
- package.json
This PR implements improvements to the package issues when running the `info` command.
- It adds a link to the issue details page for each issue listed
- It displays the human readable name of the issues
> Add link and human readable issue names

- package.json
> Release for v0.9.1

- lib/commands/cdxgen/index.js
- lib/commands/index.js
- package-lock.json
- package.json
- test/socket-cdxgen.test.js
This makes it more clear the command we forward to.
> Rename cyclonedx commant to cdxgen

- lib/commands/cdxgen/index.js
- lib/utils/path-resolve.js
Change CycloneDX output from `socket-cyclonedx.json` to `socket-cdx.json`
> Change CycloneDX output from socket-cyclonedx.json to socket-cdx.json

- package-lock.json
- package.json
Ensure the `@jdalton/packageurl-js` is used for `cdxgen`
* Reorganized field order to align with depscan _(no entries  beyond `overrides` added or changed)_
> Ensure the @jdalton/packageurl-js is used for cdxgen

- package-lock.json
- package.json
- Fixes modern NPM integration
> Release v0.10.1

- package-lock.json
- package.json
- Introduce the `organizations` command
> Release v0.11.0

- package-lock.json
Giving the package-lock a rebuild after the refactor.
> Rebuild package-lock.json

- package-lock.json
- package.json
Update @jdalton/packageurl-js dep
> Update @jdalton/packageurl-js dep

- package-lock.json
- package.json
Update `@jdalton/packageurl-js` dep again since the previous version had a typo bug in it.
> Update @jdalton/packageurl-js dep again

- package.json
Minor package.json reordering
* Merge after https://github.com/SocketDev/socket-cli-js/pull/199
> Minor package.json reordering

- package.json
[et tu, brute?](https://nl.wikipedia.org/wiki/Et_tu,_Brute%3F)
> Add `npm run testu` for simpler snapshot updating

- .dep-stats.json
- package-lock.json
- package.json
- src/commands/fix/pnpm-fix.ts
- src/utils/lockfile/pnpm-lock-yaml.ts
> Fix missing pnpm peer dep

- src/commands/fix/git.ts
- src/commands/fix/npm-fix.ts
- src/commands/fix/open-pr.ts
- src/commands/fix/pnpm-fix.ts
- src/commands/optimize/add-overrides.ts
Add workspace support to fix command
> Add workspace support to fix command

- src/commands/info/cmd-info.ts
> Hide the info command

- src/commands/manifest/cmd-manifest-gradle.test.ts
- src/commands/manifest/cmd-manifest-gradle.ts
- src/commands/manifest/cmd-manifest-kotlin.test.ts
- src/commands/manifest/cmd-manifest-kotlin.ts
- src/commands/manifest/cmd-manifest-scala.test.ts
- src/commands/manifest/cmd-manifest-scala.ts
> Dont show multi-target warning unless violated

- src/commands/scan/cmd-scan-create.test.ts
- src/commands/scan/cmd-scan-create.ts
> Add repo/branch mention in help

- src/commands/login/attempt-login.ts
- src/commands/logout/attempt-logout.ts
If only we had an AI code reviewer that could catch this.
> Fix readonly config logic

- src/utils/package-environment.ts
Use more editablePkgJson.content
> Use more editablePkgJson.content

- src/utils/arborist-helpers.ts
Make updatePackageJsonFromNode return a boolean
> Make updatePackageJsonFromNode return a boolean

- src/commands/manifest/cmd-manifest-auto.ts
> Support .yaml too in manifest auto

- src/commands/fix/git.ts
Add nested lock files when creating commits for fix command
> Add nested lock files when creating commits for fix command

- .config/babel.config.js
- .config/rollup.base.config.mjs
> Reduce build config

- .config/rollup.base.config.mjs
- .config/rollup.dist.config.mjs
- package-lock.json
- package.json
- patches/blessed#0.1.81.patch
- patches/blessed-contrib#4.11.0.patch
- patches/brace-expansion#2.0.1.patch
- src/commands/analytics/display-analytics.ts
> Fix blessed-contrib inlining

- package.json
> Fix the npm bs script

- .config/tsconfig.base.json
- src/shadow/npm/arborist/lib/arborist/types.ts
- src/utils/alert/fix.ts
- src/utils/alert/severity.ts
- src/utils/objects.ts
- src/utils/socket-package-alert.ts
Add erasableSyntaxOnly ts config
> Add erasableSyntaxOnly ts config

- src/cli.ts
- src/commands/analytics/output-analytics.test.ts
- src/commands/audit-log/output-audit-log.ts
- src/commands/cdxgen/run-cyclonedx.ts
- src/commands/fix/cmd-fix.test.ts
- src/commands/fix/git.ts
- src/commands/fix/npm-fix.ts
- src/commands/fix/open-pr.ts
- src/commands/fix/pnpm-fix.ts
- src/commands/logout/cmd-logout.test.ts
- src/commands/npm/cmd-npm.test.ts
- src/commands/npx/cmd-npx.test.ts
- src/commands/oops/cmd-oops.test.ts
- src/commands/raw-npm/cmd-raw-npm.test.ts
- src/commands/raw-npx/cmd-raw-npx.test.ts
- src/commands/report/cmd-report-create.test.ts
- src/commands/report/cmd-report-view.test.ts
- src/constants.ts
- src/instrument-with-sentry.ts
- src/shadow/npm/arborist/lib/arborist/index.ts
- src/shadow/npm/bin.ts
- src/utils/api.ts
- src/utils/config.ts
- src/utils/meow-with-subcommands.ts
- src/utils/npm.ts
- src/utils/objects.ts
- src/utils/sdk.ts
Simplify, consolidate, and normalize env var lookups
> Simplify, consolidate, and normalize env var lookups

- test/socket-npm.test.ts
> Fix npm test by removing npm8

- src/commands/analytics/output-analytics.test.ts
> Skip another test

- .github/workflows/types.yml
> Fix types workflow

- package-lock.json
- package.json
- src/commands/fix/npm-fix.ts
- src/commands/fix/pnpm-fix.ts
- src/constants.ts
- src/utils/alerts-map.ts
- src/utils/arborist-helpers.ts
- src/utils/pnpm.ts
- src/utils/socket-package-alert.ts
- src/utils/spec.ts
Add support for pnpm v8 lockfiles to fix command
> Add support for pnpm v8 lockfiles to fix command

- src/commands/fix/cmd-fix.test.mts
- src/utils/package-environment.mts
Fix snapshot tests for fix command
> Fix snapshot tests for fix command

- src/commands/fix/cmd-fix.mts
- src/commands/fix/npm-fix.mts
- src/commands/fix/pnpm-fix.mts
- src/commands/fix/shared.mts
- src/commands/fix/types.mts
- src/utils/alerts-map.mts
- src/utils/socket-package-alert.mts
Add --limit flag to fix command
> Add --limit flag to fix command

- src/commands/fix/npm-fix.mts
- src/commands/fix/pnpm-fix.mts
Reset state when bailing early in fix loop
> Reset state when bailing early in fix loop

- .config/rollup.base.config.mjs
- .config/rollup.dist.config.mjs
- src/commands/analytics/output-analytics.mts
- src/commands/npm/wrap-npm.mts
- src/commands/npx/wrap-npx.mts
- src/commands/threat-feed/output-threat-feed.mts
- src/instrument-with-sentry.mts
- src/utils/translations.mts
Wire up more modules to work with node TS
> Wire up more modules to work with node TS

- src/commands/repos/handle-create-repo.mts
- src/commands/repos/output-create-repo.mts
Make `outputCreateRepo` not async
> Make outputCreateRepo not async

- src/commands/cdxgen/cmd-cdxgen.mts
> Update cdxgen flags

- src/commands/cdxgen/cmd-cdxgen.mts
Log info about cdxgen --lifecycle when running cdxgen
> Log info about cdxgen --lifecycle when running cdxgen

- src/commands/fix/git.mts
- src/commands/scan/generate-report.mts
- src/commands/scan/generate-report.test.mts
- src/utils/socket-url.mts
- Fixes bad socket package urls
> Fix socket package urls

- src/commands/scan/fetch-report-data.mts
- src/commands/scan/output-scan-report.mts
> Minor typos

- src/commands/cdxgen/cmd-cdxgen.mts
Set cdxgen defaults when NOT passing the --help flag
> Set cdxgen defaults when NOT passing the --help flag

- src/utils/sdk.mts
Minor cleanup to TOKEN_PREFIX use
> Minor cleanup to TOKEN_PREFIX use

- src/commands/audit-log/cmd-audit-log.mts
- src/commands/audit-log/cmd-audit-log.test.mts
- src/commands/scan/cmd-scan-diff.mts
- src/commands/scan/output-diff-scan.mts
- src/commands/scan/output-scan-view.mts
- src/constants.mts
- src/utils/socket-url.mts
> Add SOCKET_WEBSITE_URL

- src/utils/socket-url.mts
> Minor cleanup to socket-url

- src/constants.mts
> Use constants.homePath

- .gitignore
- bin/cli.js
- bin/npm-cli.js
- bin/npx-cli.js
- eslint.config.js
- package-lock.json
- package.json
- src/commands/fix/open-pr.mts
- src/constants.mts
- src/shadow/npm/bin.mts
- src/shadow/npm/install.mts
Add support for v8 compile cache
> Add support for v8 compile cache

- .config/babel.config.js
- scripts/babel/transform-url-parse-plugin.js
Add babel plugin to transform `util.parse(...)` into `new URL(...)`
> Add babel plugin to transform util.parse(...) into new URL(...)

- src/shadow/npm/bin.mts
Use Node permissions for shadow-bin
> Use Node permissions for shadow-bin

- src/commands/fix/git.mts
Ensure git identity is created for prs
> Ensure git identity is created for prs

- src/commands/fix/npm-fix.mts
- src/commands/fix/pnpm-fix.mts
Skip to next package when not found in lockfile
> Skip to next package when not found in lockfile

- src/commands/fix/npm-fix.mts
- src/commands/fix/pnpm-fix.mts
> Fix dedents in fix command

- src/commands/fix/npm-fix.mts
- src/commands/fix/pnpm-fix.mts
Prep for checking open prs in fix
> Prep for checking open prs in fix

- src/commands/scan/cmd-scan-reach.test.mts
> Add snapshot for reach command

- src/commands/scan/create-scan-from-github.mts
We were too silent around errors.
This tweaks it a bit. Slightly more regular output. Way more debug output.
> Make socket scan github more verbose when errors happen

- .config/rollup.base.config.mjs
- .config/rollup.dist.config.mjs
- scripts/constants.js
- src/commands/scan/cmd-scan-reach.mts
- src/commands/scan/scan-reachability.mts
- src/constants.mts
Move coana dep to external and start integration
> Move coana dep to external and start integration
