SocketDev/socket-cli

- README.md
- lib/commands/info/index.js
- lib/commands/report/create.js
- lib/commands/report/index.js
- lib/commands/report/view.js
- lib/utils/api-helpers.js
- lib/utils/format-issues.js
This adds a first version of a `socket report view` command + enables one to use it directly with `socket report create` through the `--view` flag, waiting for the report to be created first.
The output for the report is pretty much the same as for the `socket info` command, reusing the same formatting.
The `--view` flag reuses the relevant parts of the `socket report view` command and gets fed the relevant flags of the `socket report create` command (the `--json` and `--markdown` flags) – thus making it possible to directly forward the full JSON response from the API to somewhere else.
> Add `socket report view` command + `--view` flag on `socket report create`

- cli.js
- lib/utils/update-notifier.js
- package.json
Alternative to #8 with a module that pulls in more dependencies, but which also have more features and eg. defers printing the result until the script quits, disables itself on CI, always prints to stderr etc
Has quite a few more users as well. A good first step to try this out probably.
> Add `update-notifier`

- README.md
- lib/commands/info/index.js
- lib/commands/report/create.js
- lib/commands/report/view.js
- lib/utils/format-issues.js
- lib/utils/misc.js
- tsconfig.json
To facilitate easy use in eg. CI environments a `--strict` flag has been added to fail with an exit code if any issues are found.
To ensure the usability of that command, plus to prepare for more comprehensive future outputs, all issues lower than `high` are now filtered out by default and a new flag `--all` is added to add these back in.
> Add `--strict` and `--all` to commands

- lib/commands/info/index.js
- lib/commands/report/create.js
- lib/commands/report/view.js
- lib/flags/index.js
- lib/flags/output.js
- lib/flags/validation.js
- lib/utils/flags.js
- lib/utils/formatting.js
To ensure that the different commands stay in line with one another and consistent (+ to make the code a bit more DRY and easier to follow) this PR introduces reusable structured flags.
The reusable structured flags combines the flag settings with the help list explanation and does so in a way that preserves the `meow` typing and thus still ensures a correct typing of the `.flags` result from `meow`
All in all, thus should make it easier to make a more reusable formatting setup – for help text as well as for command output.
> Reusable structured flags

- .github/workflows/provenance.yml
This will create an `npm publish` whenever a release is created on GH with proper npm provenance.
> Add npm provenance GH action

- lib/shadow/global.d.ts
- lib/shadow/npm-injection.cjs
- package.json
- test/path-resolve.spec.js
- tsconfig.json
this handles subshells that have tty removed by making an ipc bridge to the original pid
> tty ipc to mitigate subshells prompts

- lib/commands/info/index.js
This PR displays the package's scores when running the `socket info` command. To make it more visually appealing, I used a green color for scores over 80, an orange for scores between 60 and 80, and red for lower scores.
Example: Running `socket info info webtorrent@1.9.1` will display the following results.
Running `socket info info iconfront@3.1.0`:
> Add package scores to "socket info" command

- lib/commands/info/index.js
At the moment, when running `socket info`, the number of critical and high severity issues is displayed but we're not showing what the issues actually are. This PR displays the issue types as well as the number of occurrences.
I also thought it would make more sense to refactor the code so the info is displayed in the following order:
- Package scores
- Number of issues
- Issue details
- Link to package info
> Render issues when running `socket info`

- lib/commands/npm/index.js
- lib/shadow/npm-injection.cjs
npm v10.6.0 + doesn't have the module `npmlog` as dependency anymore. Instead, it uses `proc-log` so I updated our wrapper to import the correct module based on the npm version used. Feels like a bit of a hack so let me know if you think of a better way.
> Fix logging module in newer versions of npm

- .gitignore
- lib/shadow/npm-injection.cjs
- package.json
- test/socket-npm-fixtures/npm10/package-lock.json
- test/socket-npm-fixtures/npm10/package.json
- test/socket-npm-fixtures/npm8/package-lock.json
- test/socket-npm-fixtures/npm8/package.json
- test/socket-npm.test.js
this fixes modern NPM integration
> more robustly handle npm version changes

- src/shadow/npm-cli.ts
- src/shadow/npm-injection.ts
- src/utils/path-resolve.ts
When using recent versions of node & npm, the `npmlog` module is replaced with `proc-log`. This introduced a UX bug where the `safe npm` command output was getting swallowed by the default `npm install` spinner, so when the user is prompted to accept or reject potentially malicious packages, the input disappears.
This PR implements a fix. [Demo](https://www.loom.com/share/7a59fa54237c47598625abd5446dc31b?sid=4f7d506f-4e30-44b7-9df2-8194c37b8c89)
> [fix] safe-npm spinner issue

- src/commands/audit-log.ts
- src/commands/dependencies.ts
- src/commands/organization.ts
- src/commands/report/index.ts
- src/commands/repos/create.ts
- src/commands/repos/delete.ts
- src/commands/repos/list.ts
- src/commands/repos/update.ts
- src/commands/repos/view.ts
- src/commands/scan/create.ts
- src/commands/scan/delete.ts
- src/commands/scan/list.ts
- src/commands/scan/metadata.ts
- src/commands/scan/stream.ts
This PR implements error handling on commands that require the user to be authenticated.
For example, if a user is not logged into the CLI and tries to run the command `socket dependencies` or `socket organizations`, the following error message will be displayed:
```
✖ Authentication error: User must be authenticated to run this command. To log in, run the command `socket login` and enter your API key.
```
> [fix] Refactor to add auth error handling

- src/commands/scan/create.ts
Added an explicit hint to tell you which part you are missing from the command.
Before:
After:
> scan create: show users which fields are missing

- package-lock.json
- package.json
This will fix our npm audit warnings when doing `npm i`
- the xml2js bump basically forced `Object.create(null)`. This is a transitive dep of blessed-contrib. I checked `socket analytics` and that seems to still work.
- the `vite` was to get beyond an `esbuild` dep, transitive to vitest. if vitest breaks we'll know why (:
- the `undici` bump was from 6.12.0 to 6.12.1, the last in the 6.x.x branch (and a backport). It fixes how the number is generated, which I don't expect to actually break anything as the result before and after is a perceived random value of the same structure.
Before:
```
added 1 package, removed 8 packages, and audited 1248 packages in 2s
235 packages are looking for funding
run `npm fund` for details
6 moderate severity vulnerabilities
To address issues that do not …
```
> Force resolve packages beyond npm audit reports

- src/utils/api.ts
Calling `.error()` on the spinner does not stop the spinner, which leads to slightly unexpected terminal results in some cases. We should make sure it stops in this case.
> Make spinner stop after emiting handled api error

- src/commands/scan/cmd-scan-create.ts
- src/commands/scan/create-full-scan.ts
- src/commands/scan/suggest-org-slug.ts
- src/commands/scan/suggest-repo-slug.ts
- src/commands/scan/suggest_branch_slug.ts
- src/commands/scan/suggest_target.ts
- test/dry-run.test.ts
This PR updates the `socket scan create` command in a few ways
- Most importantly it adds a suggestion flow
- When certain flags or args are missing it will use the Socket API to try and make reasonable suggestions
- When the target is missing it will ask to confirm the target to be the current working directory
- It will still fail "early" if any of these values are missing after the suggestion flow
- Adds a `--read-only` flag, which is similar to the `--dry-run` flag except it will make REST API calls that only read (eg. no permanent changes)
- Alphabetically orders the function args/params
- Pushes up the error bailout if no api token is present, allowing to better separate the command file logic from the rest
- Fixes `spinner.success` to call `spinner.successAndStop` instead
Here's an …
> Add suggestion flows to `socket scan create`

- src/commands/diff-scan/get-diff-scan.ts
- src/commands/fix/run-fix.ts
- src/commands/info/format-package-info.ts
- src/commands/login/attempt-login.ts
- src/commands/manifest/convert_gradle_to_maven.ts
- src/commands/manifest/convert_sbt_to_maven.ts
- src/commands/report/create-report.ts
- src/commands/report/fetch-report-data.ts
- src/commands/repos/create-repo.ts
- src/commands/repos/delete-repo.ts
- src/commands/repos/update-repo.ts
- src/commands/scan/delete-full-scan.ts
This will a few fix cases where the spinner does not stop spinning due to an api change.
More to come.
> Stop spinners in report flow

- src/commands/analytics/cmd-analytics.ts
- src/commands/analytics/display-analytics.ts
- src/commands/analytics/fetch-org-analytics.ts
- src/commands/analytics/fetch-repo-analytics.ts
- src/utils/markdown.ts
This is about the `socket analytics` command:
- Supports the `--markdown` flag, which was previously advertised but completely ignored
- Including the `--file` flag for it, just like `--json`
- JSON to file will be formatted
- JSON to stdout will be same as the one written to file
- No more relying on `console.log` to do the formatting, or to hit depth limits
- JSON serialization separately trapped
- A bit redundant but it's possible for .stringify to hit cicular refs and fail hard
- Fixed up the typing such that the SDK types are properly reflected
- Added some input error conditions which are hidden by default
> Cleanup analytics command, support markdown

- package.json
- src/commands/audit-log/cmd-audit-log.ts
- src/commands/audit-log/get-audit-log.ts
- test/dry-run.test.ts
The `socket audit-log` claimed to support the `--json` and `--markdown` flags, but actually ignored them. Now they work.
The default will still do the interactive log cycle thing. I find it a bit confusing since it appears to be a picker of sorts but it doesn't really do anything, other than scroll. But that's a next step problem.
> Implement --json and --markdown for audit-log

- src/commands/info/cmd-info.ts
- src/commands/info/fetch-package-info.ts
- src/commands/info/format-package-info.ts
- src/commands/info/get-package-info.ts
Fixes output for the `fix` command;
- A call to `spinner.success() and `.error()` meant the spinner did not stop and as such it's swallowing output and leading to infinite spinner loop.
- Consolidated the outputs into a single param like with the others
- Cleaned up markdown and made it more markdown-y
Before;
After;
> Cleanup output for info command

- package.json
- src/commands/dependencies/find-dependencies.ts
- src/commands/diff-scan/cmd-diff-scan-get.ts
- src/commands/diff-scan/cmd-diff-scan.ts
- src/commands/diff-scan/get-diff-scan.ts
- test/dry-run.test.ts
Updates the diff-scan command;
- Fix the endpoint being fetched
- Hide the command
- In its current form it's not likely to be very useful to users. Additionally, the command was broken up to this point because it was trying to reach an endpoint that didn't exist. We'll probably want to expose this again once we solve the UX around it, and even then, probably under the `scan` command.
- Support a `--depth` flag to control how deep a JSON structure it can print
- Fixup the `--json` and `--file flags
- Support a `-` value for `--file` to explicitly dump the raw JSON to stdout
- This way you can pipe the json to another command like `socket diff-scan get | jq`
- Removed the flag for `--markdown`, I'm not sure it makes sense for this command. Or maybe it does but it would emit a high overview …
> Scrub and hide the diff-scan command

- src/commands/login/attempt-login.ts
Minor tweak but let's just be explicit in stopping the spinner for now. We'll revisit this later when we undoubtedly add some kind of "logOk" and "logErr" method to the spinner to abstract this "start-if-not-running" state.
(I think we'll want to have some kind of consistent "OK" and "ERROR" prompt in the CLI, down the road. The spinner is key here right now.)
> Be explicit with logger in login

- src/commands/manifest/convert_gradle_to_maven.ts
- src/commands/manifest/convert_sbt_to_maven.ts
Basically just making sure the spinner stops in case of trouble.
The `process.exit(1)` cases have been replaced with `process.exitCode = 1; return`
> Manifest: Better handling of spinner and exit

- src/commands/audit-log/get-audit-log.ts
- src/commands/raw-npm/cmd-raw-npm.ts
- src/commands/raw-npx/cmd-raw-npx.ts
- src/commands/report/cmd-report-create.ts
- src/commands/report/cmd-report-view.ts
- src/commands/report/cmd-report.ts
- src/commands/report/create-report.ts
- src/commands/scan/cmd-scan-create.ts
- src/commands/scan/cmd-scan-del.ts
- src/commands/scan/cmd-scan-list.ts
- src/commands/scan/cmd-scan-metadata.ts
- src/commands/scan/cmd-scan-view.ts
- src/commands/scan/cmd-scan.ts
- src/commands/scan/create-full-scan.ts
- src/commands/scan/delete-full-scan.ts
- src/commands/scan/get-full-scan-metadata.ts
- src/commands/scan/get-full-scan.ts
- src/commands/scan/list-full-scans.ts
- src/commands/scan/stream-full-scan.ts
- src/commands/scan/view-full-scan.ts
- src/utils/markdown.ts
- src/utils/path-resolve.ts
- test/dry-run.test.ts
- test/path-resolve.test.ts
Deprecates and hides the `socket report` command, updates the `socket scan` command with a `socket scan view` command (supplementing the `socket scan stream`), updated some markdown/json flows.
- The `socket report` commands are now hidden and marked as deprecated explicitly
- The `socket report view` command idea is added to the `scan` suite
- There's one feature that `socket report create` had that `scan` does not yet; using a file based config. We'll have to think about this a bit more before we codify that forever, but before the next version bump. Other than that they were equal already.
- Added a `socket scan view` command, which kind of replaces the `socket scan stream`
- `stream` does not convey the same message as `view`
- The thing `stream` did is kept though; it'll stream the …
> Cleanup scan, merge report stuff, hide report command

- src/constants.ts
- src/utils/meow-with-subcommands.ts
- test/dry-run.test.ts
This enables the Socket ascii art banner at the top of every command and help screen.
It looks roughly like this:
```
_____         _       _        /---------------
|   __|___ ___| |_ ___| |_      | Socket.dev CLI ver 0.14.57:a70bc02:72eb3827:dev
|__   | . |  _| '_| -_|  _|     | Node: v20.18.2, API token set: 19tED
|_____|___|___|_,_|___|_|.dev   | Command: `socket`, cwd: ~/socket/socket-cli
```
This banner contains versioning, login status, command executed (without flags), and the cwd.
This will help us with debugging when people include this in their report.
The banner is emitted over stderr (just like the spinner) and should not interfere with output that's meant to be piped through.
> Enable banner by default over stderr

- src/commands/audit-log/cmd-audit-log.ts
- src/commands/threat-feed/cmd-threat-feed.ts
- src/commands/threat-feed/get-threat-feed.ts
This fixes the threat feed and improves the CLI side of things a bit;
- Fixes the queries (right now it defaulted to fetching zero entries...)
- Added an `ecoSystem` filter to only fetch reports for maven or npm or whatever
- Updated the help to explain the different filter options and what they mean
- Added a description box for the interactive table view; it will show the details for the highlighted row as well as the "description" verdict which explains why a package was flagged.
- Fixed date "ago" strings
- Tried to fix some UI glitches with column positioning. Mostly hacked around the table not properly calculating column widths for some cases, leading to a wrangled table view. In its current form it works and stuff is aligned, at least. We'll revisit this later.
Sample:
> Fix threat-feed, improve ui, add eco filter

- src/utils/path-resolve.ts
This enables the glob for including ruby and dotnet files when doing a scan.
Closes ENG-3172
> Enable ruby and .net ecosystems for scan

- src/commands/scan/cmd-scan-report.ts
- src/commands/scan/generate-report.test.ts
- src/commands/scan/generate-report.ts
- src/commands/scan/report-full-scan.test.ts
- src/commands/scan/report-full-scan.ts
- src/utils/walk-nested-map.test.ts
- src/utils/walk-nested-map.ts
Main purpose of this PR is to add `--markdown` support to `socket scan report`. See tests for example what that looks like.
Stuff was abstracted and cleaned up, too. Tests were added.
The json report now includes the org slug, the scan id, and the fold/reportlevel settings used to generate the report.
> [scan report] Support markdown, cleanup, add tests

- test/utils.ts
Sometimes 10s just isn't enough to sip your coffee and eat your lunch and finish tests that should take 2s and read the newspaper.
> Increase test timeout to 30s to please the CI flakiness

- src/commands/scan/cmd-scan-report.test.ts
- src/commands/scan/cmd-scan-report.ts
- src/commands/scan/generate-report.ts
- src/commands/scan/report-full-scan.ts
Adds a --short flag to `socket scan report` to have brief outputs intended for CI/automated usages. Will report OK/ERR by default, `{healthy:boolean}` for JSON, and `healthy = boolean` in markdown modes.
Also made exit code reflect `healthy:false` state (regardless of output mode).
> [scan report] Add --short flag for CI type of use cases

- src/utils/settings.ts
Small cleanup around the settings util
- Remove `any`
- Describe the target folder semantics
- Pull module-globals up to the top
> Refactor the settings handling

- src/commands/package/cmd-package-shallow.ts
- src/commands/package/fetch-purls-shallow-score.ts
- src/commands/package/handle-purls-shallow-score.ts
- src/commands/package/output-purls-shallow-score.ts
- src/utils/api.ts
- src/utils/sdk.ts
Started to realize an emerging pattern;
Command file does initial handling, then usually fetches (or collects) data before displaying (or transmitting) it.
Going to make that more consistent in all commands, here's a sample: use `handle-` for the "bridging" file. Basically this is the command being invoked without the input handling/validation. Or put differently, everything that happens after dry-run exits.
Then there's a `fetch-*` file for collecting the data from the API. This may be different for files that collect data from disk or whatever but at least most of the "get-" should become "fetch-".
And the last file is `output-*` to display the result to the user, or to write it to disk or something.
I suspect that most `fetch-` stuffs can be abstracted pretty decently as part of our …
> Refactor package filename to handle-* fetch-* and output-*

- src/commands/diff-scan/cmd-diff-scan-get.ts
- src/commands/diff-scan/fetch-diff-scan.ts
- src/commands/diff-scan/handle-diff-scan.ts
- src/commands/diff-scan/output-diff-scan.ts
Refactors the diff-scan command
> Apply handle pattern to diff-scan

- package-lock.json
- package.json
Bump vite to 6.2.3 because < trigger warnings.
We don't even care about vite but it's a transitive dep for vitest :shrug:
> Vump Vite Vo Vix Vuln Version

- src/utils/config.ts
Let's migrate `apiKey` out of the config.
After this PR, when the CLI loads the config, if it see the `apiKey` property set it will delete it and write its value to `apiToken` instead. It will then persist the config.
This way users should automatically migrate to the new key and in a next major bump we can remove this migration logic. Anyone who wasn't auto-migrated will simply be considered logged out so they can `socket login` to remedy that, no big deal.
> Migrate apiKey to apiToken if it occurs

- src/utils/api.ts
This adds a way to override the base url for local development. When not given through env or config, use the default.
Also add a better message when the remote responds with 404. This shouldn't happen but that doesn't mean it won't.
> Fix getting the API base url and 404 error message

- src/commands/audit-log/audit-fixture.json
- src/commands/audit-log/output-audit-log.test.ts
- src/commands/audit-log/output-audit-log.ts
The old output without markdown/json was using a select interaction but it didn't really make sense tbh. So instead I dropped it and default to the markdown report.
Added a fixture and tests to cover the output.
> Make audit-logs default to markdown report, add test

- src/commands/scan/fetch-create-org-full-scan.ts
- src/commands/scan/fetch-supported-scan-file-names.ts
- src/commands/scan/handle-create-new-scan.ts
- src/utils/api.ts
- src/utils/path-resolve.ts
- Improved messaging on some logs
- Improved spinner handler and output while creating a new scan
> Small loggin refactors/improvements

- src/commands/scan/cmd-scan-report.test.ts
- src/commands/scan/cmd-scan-report.ts
- src/commands/scan/fetch-report-data.ts
- src/commands/scan/generate-report.test.ts
- src/commands/scan/generate-report.ts
- src/commands/scan/handle-scan-report.ts
- src/commands/scan/output-scan-report.test.ts
- src/commands/scan/output-scan-report.ts
Enables reporting license violations with `socket scan report`. It is disabled by default but you can enable it with the `--license` flag. When enabled, it will receive license-related violation alerts from the server as well and can act on them accordingly.
> Allow optional license reporting of scan report

- src/commands/config/cmd-config-get.test.ts
- src/commands/config/cmd-config.test.ts
- src/commands/config/handle-config-get.ts
- src/commands/config/handle-config-set.ts
- src/commands/config/output-config-get.ts
- src/commands/config/output-config-list.ts
- src/commands/config/output-config-set.ts
- src/commands/login/attempt-login.ts
- src/commands/logout/attempt-logout.ts
- src/utils/config.ts
- src/utils/meow-with-subcommands.ts
- test/utils.ts
- Fixes using the `SOCKET_SECURITY_API_TOKEN` env var. Also supports API_KEY and the prefix SOCKET_CLI for consistency. In a next major we'll probably deprecate the KEY variants.
- Make the CLI emit a proper error message when the config override cannot be parsed, rather than a generic JSON error with stack trace.
- Add some tests around this
- Add notice to `config` commands when the config is in read-only mode
- Warn when logging in/out while config is in read-only mode
> Polish the config/token override stuff

- src/commands/scan/cmd-scan-create.test.ts
- src/commands/scan/cmd-scan-create.ts
- src/commands/scan/handle-create-new-scan.ts
- src/commands/scan/output-create-new-scan.ts
The old report workflow, attached to `socket ci`, is to do create a report and then ask for the results in a report view. While you could do the same in the scan creation flow, it would require some slightly awkward shell script to handle the json result and fire a report request etc. Anyways, `--report` takes care of that.
The only concern is a timeout from the server while waiting for the scan to complete...
Also clarified flags desc for pendingHead and defaultBranch a bit.
Fixed a bug with `defaultOrg` (nobody uses this yet) with the suggestion flow.
Added support for `--json` and `--markdown` in the `socket scan create` flow. A bit superficial but it does what it should do.
> Add --report to socket scan create, to immediately generate a report

- src/cli.ts
- src/commands/scan/cmd-scan-create.ts
- src/utils/path-resolve.ts
When doing `scan report create .` we special case the dot to `*/**`.
But when somebody uses `./` instead the result fails.
This PR will also map `./` to the `*/**` glob.
This PR will also cleanup a few stack traces and error artifacts and tuck them under a debug log instead.
> Support `./` for scan create too

- src/commands/scan/handle-create-new-scan.ts
Fixes a confusing 400 response from the server when trying to create a scan without any files.
> When scan create has no files, do not proceed to upload

- src/commands/info/cmd-info.test.ts
- src/commands/info/cmd-info.ts
- src/commands/package/cmd-package-score.test.ts
- src/commands/package/cmd-package-score.ts
- src/commands/package/cmd-package-shallow.test.ts
- src/commands/package/cmd-package-shallow.ts
- src/commands/package/cmd-package.test.ts
- src/commands/package/cmd-package.ts
The new package commands were hidden while we were testing the API. Time is right to open them up.
> Unhide package commands with beta tag

- src/cli.ts
- src/commands/scan/cmd-scan-create.test.ts
- src/commands/scan/cmd-scan-create.ts
- src/commands/scan/fetch-create-org-full-scan.ts
- src/commands/scan/handle-create-new-scan.ts
Remove the --view flag, which wasn't doing anything
Connect the various commit meta data flags, which were not forwarding the data to the API call
> Fix flags of scan create

- src/commands/scan/cmd-scan-create.ts
- src/commands/scan/cmd-scan-del.ts
- src/commands/scan/cmd-scan-list.ts
- src/commands/scan/cmd-scan-metadata.ts
- src/commands/scan/cmd-scan-report.ts
- src/commands/scan/cmd-scan-view.ts
It's easy to overlook and not super intuitive that you need to enter the orgslug in the first place.
But that's how it was and we'll fix it in a major. For now, try to guide the user to resolve the issues faster by a clearer message.
> Give better signal that orgslug is missing

- src/commands/repos/cmd-repos-create.test.ts
- src/commands/repos/cmd-repos-create.ts
- src/commands/repos/cmd-repos-del.test.ts
- src/commands/repos/cmd-repos-del.ts
- src/commands/repos/cmd-repos-update.test.ts
- src/commands/repos/cmd-repos-update.ts
- src/commands/repos/cmd-repos-view.test.ts
- src/commands/repos/cmd-repos-view.ts
- src/commands/scan/cmd-scan-create.ts
> Polish a few input errors

- src/commands/report/cmd-report-create.ts
- src/commands/report/cmd-report-view.ts
- src/commands/repos/cmd-repos-create.test.ts
- src/commands/repos/cmd-repos-create.ts
- src/commands/repos/cmd-repos-update.test.ts
- src/commands/repos/cmd-repos-update.ts
- src/commands/repos/cmd-repos-view.test.ts
- src/commands/repos/cmd-repos-view.ts
- src/commands/scan/cmd-scan-metadata.test.ts
- src/commands/scan/cmd-scan-metadata.ts
Some flags were mandatory but the help was not being obvious about that.
> Polish the usage hints in help in some cases

- src/commands/package/fetch-purl-deep-score.ts
- src/commands/package/fetch-purls-shallow-score.ts
- src/commands/package/parse-package-specifiers.test.ts
- src/commands/package/parse-package-specifiers.ts
Apparently we couldn't do something like `socket score npm @babel/core`. This fixes it.
> Fix namedspaced purl parsing for package commands

- src/commands/fix/npm-fix.ts
- src/commands/fix/pnpm-fix.ts
- src/utils/arborist-helpers.ts
Make npm fix on par with pnpm fix
> Make npm fix on par with pnpm fix

- src/commands/analytics/cmd-analytics.ts
- src/commands/audit-log/cmd-audit-log.ts
- src/commands/config/cmd-config-set.ts
- src/commands/config/cmd-config-unset.ts
- src/commands/dependencies/cmd-dependencies.ts
- src/commands/diff-scan/cmd-diff-scan-get.ts
- src/commands/info/cmd-info.ts
- src/commands/manifest/cmd-manifest-gradle.ts
- src/commands/manifest/cmd-manifest-kotlin.ts
- src/commands/manifest/cmd-manifest-scala.ts
- src/commands/organization/cmd-organization-list.ts
- src/commands/organization/cmd-organization-policy-license.ts
- src/commands/organization/cmd-organization-policy-security.ts
- src/commands/organization/cmd-organization-quota.ts
- src/commands/package/cmd-package-score.ts
- src/commands/repos/cmd-repos-create.ts
- src/commands/repos/cmd-repos-del.ts
- src/commands/repos/cmd-repos-list.ts
- src/commands/repos/cmd-repos-update.ts
- src/commands/repos/cmd-repos-view.ts
- src/commands/scan/cmd-scan-create.ts
- src/commands/scan/cmd-scan-del.ts
- src/commands/scan/cmd-scan-list.ts
- src/commands/scan/cmd-scan-metadata.ts
- src/commands/scan/cmd-scan-report.ts
- src/commands/scan/cmd-scan-view.ts
- src/commands/threat-feed/cmd-threat-feed.ts
- src/commands/wrapper/cmd-wrapper.ts
- src/utils/handle-bad-input.ts
- src/utils/path-resolve.ts
Create consistent property type and avoid polymorphic values
> Create consistent property type and avoid polymorphic values

- src/cli.ts
- src/commands/ci/cmd-ci.test.ts
- src/commands/ci/cmd-ci.ts
- src/commands/ci/fetch-default-org-slug.ts
- src/commands/ci/handle-ci.ts
- src/commands/scan/cmd-scan-create.test.ts
- src/commands/scan/cmd-scan-create.ts
- src/commands/scan/fetch-report-data.ts
- src/commands/scan/generate-report.test.ts
- src/commands/scan/generate-report.ts
- src/commands/scan/output-scan-report.ts
This updates the `socket ci` command to use the `socket scan create --report` flow.
> Update CI command to use scan create flow

- src/commands/manifest/cmd-manifest-gradle.test.ts
- src/commands/manifest/cmd-manifest-gradle.ts
- src/commands/manifest/cmd-manifest-kotlin.test.ts
- src/commands/manifest/cmd-manifest-kotlin.ts
- src/commands/manifest/cmd-manifest-scala.test.ts
- src/commands/manifest/cmd-manifest-scala.ts
These flags should be `--bin` but the examples were showing something else :(
> Fix wrong flag suggestion in manifest help

- src/commands/manifest/cmd-manifest-gradle.test.ts
- src/commands/manifest/cmd-manifest-gradle.ts
- src/commands/manifest/cmd-manifest-kotlin.test.ts
- src/commands/manifest/cmd-manifest-kotlin.ts
- src/commands/manifest/convert_gradle_to_maven.ts
- Fix relative path args not properly resolving for `socket manifest gradle` (and kotlin, which uses same logic)
- Fix `--cwd` flags for these commands, they were being ignored
- Remove the `--out` and `--stdout` flags for these commands, they were being ignored and it's not actually realistic to make them work
- Make the core logic resolve the input paths against the cwd, defaulting to `process.cwd()`
- Internally, this should also prevent the globber package we use from complaining about relative paths
- Tried to cleanup spiner logic and put it tight around gradlew execution. I think the spinner is currently not working completely as I don't see a spinner running. Not sure what's up there. End message is printed though.
- Warn more explicitly when input paths cannot be resolved.
- Only …
> Fix `socket manifest gradle/kotlin` pathing

- src/commands/scan/output-list-scans.ts
This adds a `repo` column in the `socket scan list` so you can see the repo to which a scan belongs. Weird that it was missing but eh.
> Show repo in scan list

- src/commands/scan/cmd-scan-list.test.ts
- src/commands/scan/cmd-scan-list.ts
- src/commands/scan/fetch-list-scans.ts
- src/commands/scan/handle-list-scans.ts
This way you can filter the `socket scan list` to look only for scans in certain repos or with certain branch names (or both). Probably handy ;)
> Add --repo and --branch filters to `socket scan list`

- src/utils/config.ts
Helps with an issue trying to figure out why the config is set to read-only. Hopefully.
> Emit debug log when config gets marked as read-only

- src/commands/fix/npm-fix.ts
- src/commands/fix/pnpm-fix.ts
Log install status after starting install
> Log install status after starting install

- src/commands/manifest/README.md
- src/commands/manifest/cmd-manifest-auto.ts
- src/commands/manifest/cmd-manifest-conda.test.ts
- src/commands/manifest/cmd-manifest-conda.ts
- src/commands/manifest/cmd-manifest.test.ts
- src/commands/manifest/cmd-manifest.ts
- src/commands/manifest/convert-conda-to-requirements.test.ts
- src/commands/manifest/convert-conda-to-requirements.ts
- src/commands/manifest/handle-manifest-conda.ts
- src/commands/manifest/output-requirements.ts
- test/socket-npm-fixtures/manifest-conda/environment.yml
The `socket manifest conda` will try to extract the pip block from a Conda environment.yml file and return it as a python requirements.txt file.
> Add `socket manifest conda` to convert to requirements.txt

- src/commands/ci/handle-ci.ts
- src/commands/scan/cmd-scan-create.test.ts
- src/commands/scan/cmd-scan-create.ts
- src/commands/scan/handle-create-new-scan.ts
- src/commands/scan/output-create-new-scan.ts
This adds a flag to `socket scan create` that will suppress any interactive asks for input.
This includes the auto-suggestion for missing input, as well as the final "do you want to view in browser" question.
There used to be a `--view` option but that was removed a while back. This would basically replace that in lieu of a more generic approach (pending).
> Add --interactive flag to scan create

- src/utils/meow-with-subcommands.ts
We should at least give people a heads up about it.
(Hm, this would cause the node 18 tests to break because snapshots. Can we maybe just turn that test runner off now in anticipation of the full deprecation?)
> Add node 18 deprecation warning to banner

- src/utils/api.ts
We recently changed the SDK to no longer drop these causes but we weren't surfacing them to the user yet.
These causes are super informational when it comes to input problems.
So now:
Not as useful for auth errors but can't hurt either
> Add the `cause` field to the API error message

- sd
`sd` is for `socket dev`, but also for running socket in dev mode.
It will invoke the src/cli.mts script with strip types and pass on args verbatim.
Now all we need to do in dev is in the root of `socket-cli` call `./sd` (which, I assure you, you get used to quite quickly).
Instant dev gratification.
> Add root shortcut "sd" to invoke the cli

- sd
This allows ./sd to run in node20 too by calling npm run.
I chose to have it call `npm run s` rather than `npm run bs` because we're most likely to use it for node 22 anyways. Adding a warning would add more noise. I dunno. We can still add a warning if we want to.
> Add node20 fallback to ./sd

- src/commands/repos/cmd-repos-create.mts
- src/commands/repos/cmd-repos-create.test.mts
- src/commands/repos/cmd-repos-del.mts
- src/commands/repos/cmd-repos-del.test.mts
- src/commands/repos/cmd-repos-list.mts
- src/commands/repos/cmd-repos-update.mts
- src/commands/repos/cmd-repos-update.test.mts
The flags themselves weren't allowed yet.
> Allow --json and --markdown in repos command

- src/commands/package/fetch-purl-deep-score.mts
- src/commands/package/fetch-purls-shallow-score.mts
- src/commands/scan/cmd-scan-report.mts
- src/commands/scan/cmd-scan-report.test.mts
- src/commands/scan/cmd-scan-view.mts
- src/commands/scan/cmd-scan-view.test.mts
- src/commands/scan/fetch-diff-scan.mts
- src/commands/scan/fetch-report-data.mts
- src/commands/scan/fetch-scan.mts
- src/commands/scan/fetch-supported-scan-file-names.mts
Some minor output fixes
- various cases of logging to stdout that was breaking --json, temporarily doing an .error() but we'll change the logger soon to always output non-log commands to stderr and then we can do a sweep through the .error() calls to see what needs to be different.
- Some textual changes and fixed some missing parenthesis in text (the bot caught one the other day but apparently didn't think it was important for the others)
> Fix output; some was breaking --json, some typos

- src/commands/package/fetch-purls-shallow-score.mts
This fixes `socket package shallow npm babel` which currently breaks due to bad API typing in SDK in OpenAI.
> Fix package shallow command due to type mismatch

- src/commands/scan/generate-report.mts
- src/commands/scan/generate-report.test.mts
- src/commands/scan/output-scan-report.mts
- src/commands/scan/output-scan-report.test.mts
The `socket scan report --json` command was not yet returning the cresult interface.
> Make scan report also return cresult interface with --json

- src/constants.mts
Add `DISABLE_GITHUB_CACHE` env var
> Add DISABLE_GITHUB_CACHE env var

- src/commands/analytics/cmd-analytics.mts
- src/commands/analytics/cmd-analytics.test.mts
- src/commands/analytics/output-analytics.mts
We are migrating this API endpoint to another endpoint and the 7 is currently not working properly. The 30 is more reliable.
> Bandaid fix for analytics command

- src/commands/analytics/cmd-analytics.mts
- src/commands/audit-log/cmd-audit-log.mts
- src/commands/config/discover-config-value.mts
- src/commands/dependencies/cmd-dependencies.mts
- src/commands/diff-scan/cmd-diff-scan-get.mts
- src/commands/organization/cmd-organization-list.mts
- src/commands/organization/cmd-organization-policy-license.mts
- src/commands/organization/cmd-organization-policy-security.mts
- src/commands/organization/cmd-organization-quota.mts
- src/commands/organization/output-organization-list.mts
- src/commands/package/cmd-package-score.mts
- src/commands/repos/cmd-repos-create.mts
- src/commands/repos/cmd-repos-del.mts
- src/commands/repos/cmd-repos-list.mts
- src/commands/repos/cmd-repos-update.mts
- src/commands/repos/cmd-repos-view.mts
- src/commands/scan/cmd-scan-create.mts
- src/commands/scan/cmd-scan-del.mts
- src/commands/scan/cmd-scan-diff.mts
- src/commands/scan/cmd-scan-list.mts
- src/commands/scan/cmd-scan-metadata.mts
- src/commands/scan/cmd-scan-report.mts
- src/commands/scan/cmd-scan-view.mts
- src/commands/threat-feed/cmd-threat-feed.mts
- src/utils/api.mts
- src/utils/meow-with-subcommands.mts
- src/utils/sdk.mts
This cleans up the `getDefaultToken()` calls a bit and replaces them with `hasDefaultToken`, which is what most callsites want to know.
Changing the visible part of the token in the banner to the first five character rather than the last, because that's what's visible in the dashboard. And ultimately it doesn't really matter which chars are visible, anyways. It's just a clue to yourself and for debugging.
> Cleanup getDefualtToken usage, show prefix of token

- src/constants.mts
Minor tweak. For the sake of consistency I think it makes sense to support the `SOCKET_CLI` prefix for the base url and proxy, too.
> Support SOCKET_CLI prefix for base url

- src/commands/oops/cmd-oops.mts
- src/commands/package/fetch-purls-shallow-score.mts
- src/utils/api.mts
This cleans up the last usage. Missed it in the previous sweep.
Also adds json/markdown flag for the oops command. Not super relevant to anyone else.
> Cleanup lsat old handleApi usage

- src/cli.mts
- src/commands/cdxgen/cmd-cdxgen.mts
- src/commands/cdxgen/cmd-cdxgen.test.mts
- src/commands/cdxgen/handle-cdxgen.mts
This makes `socket cdxgen` work again by forwarding to the new location. It will print a small deprecation warning, too.
> Create alias for toplevel cdxgen

- src/commands/analytics/output-analytics.mts
- src/commands/audit-log/cmd-audit-log.test.mts
- src/commands/diff-scan/output-diff-scan.mts
- src/commands/fix/cmd-fix.test.mts
- src/commands/manifest/cmd-manifest-conda.mts
- src/commands/manifest/cmd-manifest-conda.test.mts
- src/commands/manifest/convert-conda-to-requirements.mts
- src/commands/manifest/convert_sbt_to_maven.mts
- src/commands/organization/cmd-organization-policy-license.test.mts
- src/commands/organization/cmd-organization-policy-security.test.mts
- src/commands/organization/output-license-policy.mts
- src/commands/package/fetch-purl-deep-score.mts
- src/commands/package/fetch-purls-shallow-score.mts
- src/commands/package/output-purl-score.mts
- src/commands/repos/cmd-repos-create.test.mts
- src/commands/repos/cmd-repos-del.test.mts
- src/commands/repos/cmd-repos-list.test.mts
- src/commands/repos/cmd-repos-update.test.mts
- src/commands/repos/cmd-repos-view.test.mts
- src/commands/scan/cmd-scan-create.mts
- src/commands/scan/fetch-diff-scan.mts
- src/commands/scan/fetch-report-data.mts
- src/commands/scan/output-diff-scan.mts
- src/commands/scan/stream-scan.mts
- src/commands/threat-feed/cmd-threat-feed.test.mts
- src/commands/threat-feed/output-threat-feed.mts
- src/instrument-with-sentry.mts
- src/utils/determine-org-slug.mts
- src/utils/serialize-result-json.mts
This updates a few lingering calls to logger.error to a more apt method like .success, .warn. or .info, now that those are all going to stderr.
> Update few logger calls to better methods

- src/commands/scan/cmd-scan-create.mts
- src/commands/scan/cmd-scan-create.test.mts
This will rename the `--pendingHead` flag for `socket scan create` to `--setAsAlertsPage`.
It will unset this flag when `--tmp` is set.
Docs are updated to clarify what this flag is actually doing.
> pendingHead -> setAsAlertsPage + docs

- src/commands/manifest/cmd-manifest-auto.mts
- src/commands/manifest/detect-manifest-actions.mts
- src/commands/scan/cmd-scan-create.mts
This will make `socket manifest auto` first detect all targets and then run any found, rather than only the first one.
This detect script will also be shared with `socket scan create`, later.
> Make manifest auto detect all cases and run any found

- src/commands/manifest/setup-manifest-config.mts
- src/commands/scan/cmd-scan-create.mts
- src/commands/scan/cmd-scan-create.test.mts
- src/commands/scan/cmd-scan-github.mts
- src/commands/scan/cmd-scan-github.test.mts
- src/commands/scan/cmd-scan-setup.mts
- src/commands/scan/cmd-scan-setup.test.mts
- src/commands/scan/cmd-scan.mts
- src/commands/scan/cmd-scan.test.mts
- src/commands/scan/handle-scan-config.mts
- src/commands/scan/output-scan-config-result.mts
- src/commands/scan/setup-scan-config.mts
- src/utils/meow-with-subcommands.mts
- src/utils/socketjson.mts
This adds a `socket scan setup` which allows you to configure a few defaults for flags to `socket scan create` and `socket scan github`.
Also
- Updates the manifest side of things with small lessons learned.
- Refines the help for `scan create`
- Allows TARGET to be omitted for `scan create`, defaulting to the CWD
- Supports a CWD argument for `scan github` for the purpose of resolving the socket.json
> Add `socket scan setup` for flag defaults

- src/commands/cli.test.mts
- src/utils/meow-with-subcommands.mts
- src/utils/output-formatting.mts
Been working a bit on a new layout / overview for the root help screen.
The src/commands/cli.test.mts file should display the before (current v1) and new (v1 mode) screen.
This is what users will see now (flags update did go into this screen too, which is fine because that's the status quo):
This is what the v1 screen will look like:
> Create new --help layout for root

- eslint.config.js
We're kind of depending on `fetch` so this rule is bs.
> Allow fetched under eslint rules

- src/commands/wrapper/add-socket-wrapper.mts
- src/commands/wrapper/check-socket-wrapper-setup.mts
- src/commands/wrapper/remove-socket-wrapper.mts
(Since you can't access the session from which the command was executed, you can't remove the alias. The user will have to do this explicitly or it will naturally cycle as terminals get closed. But to state that it's active/inactive now is misleading.)
> Add warning after wrapper on/off about restarting terminal session

- src/cli.mts
- src/commands/oops/cmd-oops.mts
Improve how uncaught errors are presented to the user.
In particular, when the command uses a `--json` flag, try to respect it by emitting the CResult json rather than a plain text error message.
> Uncaught json

- src/commands/cli.test.mts
- src/utils/meow-with-subcommands.mts
Added support for a shorthand for getting package score:
```
socket pkg:npm/babel
```
The `pkg:` is optional too, if the second arg is anything that starts with a-z followed by a forward slash then it will automatically run `socket package score <...args>` on it.
If you omit the `pkg:` then the CLI will prefix it for you, which is what `socket package` already does.
> Add a shorthand for `socket <purl>` to get score

- src/cli.mts
- src/commands/json/cmd-json.mts
- src/commands/json/cmd-json.test.mts
- src/commands/json/handle-cmd-json.mts
- src/commands/json/output-cmd-json.mts
- src/utils/meow-with-subcommands.mts
- src/utils/tildify.mts
- test/socket-npm-fixtures/sjtest/socket.json
This adds `socket json [dir=.]` which will print the `socket.json` file that would be used if a supporting command worked on that directory.
We'll probably bring this under some subcommand sooner or later but for now we'll just hide it.
> Add `socket json` to dump the json file to stdout

- package-lock.json
- package.json
There's a vuln in .1 , bump to .2 looks non-breaking so let's do it.
> Bump override for undici

- src/commands/threat-feed/cmd-threat-feed.mts
- src/commands/threat-feed/cmd-threat-feed.test.mts
- src/commands/threat-feed/fetch-threat-feed.mts
- src/commands/threat-feed/handle-threat-feed.mts
This updates the threat-feed:
- switches over to the new org scoped threat-feed API endpoint (no real changes in CLI for that)
- adds support for filtering results by package name or version
- fixed an issue where having an empty default filter would result in the server rejecting it
> Threat-feed; use new api endpoint, add search flags

- src/commands/config/cmd-config-auto.test.mts
- src/commands/config/cmd-config-get.test.mts
- src/commands/config/cmd-config-set.test.mts
- src/commands/config/cmd-config-unset.test.mts
- src/commands/repository/output-list-repos.mts
- src/commands/scan/cmd-scan-create.mts
- src/commands/scan/cmd-scan-github.mts
- src/commands/scan/suggest-to-persist-orgslug.mts
- src/utils/config.mts
- src/utils/determine-org-slug.mts
This streamlines the flow where if you don't have a default org set, the CLI will interactively ask you to select one.
After selecting the org it will ask you if you want to store this setting as the default org.
If you say yes it will update the config with that org as the default org.
You can opt not to do so. You can even opt to not be asked this particular question again.
> When selecting org, ask to persist it

- .github/workflows/claude-auto-review.yml
- .github/workflows/claude.yml
This PR
-   adds workflows to enable automatic code reviews via Claude Code and ability to assign it tasks on PRs.
> Add workflows for Claude Code

- src/commands/scan/perform-reachability-analysis.mts
You can easily modify the code to bypass the check, but you won't be able to see the tier 1 results in the UI or through the API without an enterprise plan, so the check is more informational than actually restrictive.
> Add check to only allow users on the enterprise plan to run tier 1

- package-lock.json
- package.json
Upgrades the Coana CLI to fix a problem in the tier 1 analysis, where it didn't work properly for some Python projects.
> Upgrade coana cli august 27

- package-lock.json
- package.json
- src/commands/scan/perform-reachability-analysis.mts
This change ensures that Coana won't try to fetch cached analysis configuration for the default project. The default repo and branch are likely used for very different projects, so we shouldn't be using cached configuration.
- edit: Also upgrades Coana to 14.12.10 to fix various minor bugs related to the reachability analysis.
> do not pass default branch and repo name to coana CLI

- src/commands/fix/coana-fix.mts
Inherit `stdio` when running auto fixes using the Coana CLI. Made this change since it is otherwise difficult to tell if the Coana CLI is making progress.
> stdio:inherit when using Coana for fixes
